export interface GemstoneData {
  name: string;
  slug: string;
  category: string;
  color: string;
  mohs: number | string;
  ri: string;
  sg: string;
  crystal: string;
  treatments: string[];
  origins: string[];
  description: string;
  priceRange: string;
}

export const gemstones: GemstoneData[] = [
  {
    name: "Diamond",
    slug: "diamond",
    category: "Precious",
    color: "Colorless, yellow, brown, blue, pink, green, red, black",
    mohs: 10,
    ri: "2.417",
    sg: "3.52",
    crystal: "Cubic (isometric)",
    treatments: ["HPHT", "Irradiation", "Fracture filling", "Coating", "Laser drilling"],
    origins: ["Botswana", "Russia", "Canada", "Australia", "South Africa", "Namibia"],
    description: "The hardest known natural material. Diamonds are carbon crystallized under extreme pressure and temperature deep in the Earth's mantle. Valued for brilliance, fire, and durability.",
    priceRange: "$500–$20,000/ct (gem quality); $20,000+/ct (fancy colors)",
  },
  {
    name: "Ruby",
    slug: "ruby",
    category: "Precious",
    color: "Red to purplish-red",
    mohs: 9,
    ri: "1.762–1.770",
    sg: "3.97–4.05",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat", "Flux healing", "Fracture filling (lead glass)", "Surface diffusion"],
    origins: ["Myanmar (Burma)", "Mozambique", "Thailand", "Sri Lanka", "Tanzania", "Madagascar"],
    description: "Red corundum, one of the most valuable colored gemstones. Burmese 'pigeon's blood' red is the most prized. Ruby is durable and suitable for all jewelry types.",
    priceRange: "$1,000–$15,000/ct (fine); $15,000–$100,000+/ct (Burmese pigeon's blood)",
  },
  {
    name: "Sapphire",
    slug: "sapphire",
    category: "Precious",
    color: "Blue, pink, yellow, green, purple, orange, colorless, padparadscha",
    mohs: 9,
    ri: "1.762–1.770",
    sg: "3.95–4.03",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat", "Beryllium diffusion", "Surface diffusion", "Fracture filling"],
    origins: ["Sri Lanka", "Madagascar", "Myanmar", "Kashmir", "Australia", "Montana (USA)"],
    description: "All corundum colors except red. Blue is most famous — Kashmir cornflower blue is legendary. Padparadscha (pink-orange) is among the rarest.",
    priceRange: "$200–$5,000/ct (blue fine); $5,000–$30,000+/ct (Kashmir/Padparadscha)",
  },
  {
    name: "Emerald",
    slug: "emerald",
    category: "Precious",
    color: "Green to bluish-green",
    mohs: 7.5,
    ri: "1.565–1.602",
    sg: "2.67–2.78",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Fracture filling (oil, resin)", "Color enhancement", "Surface coating"],
    origins: ["Colombia", "Zambia", "Brazil", "Afghanistan", "Ethiopia", "Pakistan"],
    description: "Green beryl. Colombian emeralds with vivid color and minimal inclusions command the highest prices. Almost all emeralds are fracture-filled to improve clarity.",
    priceRange: "$500–$8,000/ct (fine); $8,000–$30,000+/ct (Colombian no-oil)",
  },
  {
    name: "Tanzanite",
    slug: "tanzanite",
    category: "Semi-precious",
    color: "Blue to violet-blue, pleochroic",
    mohs: 6.5,
    ri: "1.685–1.707",
    sg: "3.35",
    crystal: "Orthorhombic",
    treatments: ["Heat (mandatory to remove brown component)"],
    origins: ["Tanzania (single location — Merelani Hills)"],
    description: "A rare blue-violet zoisite found only in Tanzania. Strongly pleochroic — appears blue, violet, or burgundy depending on angle. Heat treatment is standard to achieve blue color.",
    priceRange: "$200–$1,200/ct (fine); $1,200–$3,500+/ct (large deep blue)",
  },
  {
    name: "Opal",
    slug: "opal",
    category: "Semi-precious",
    color: "White, black, crystal, with play-of-color (rainbow flashes)",
    mohs: 5.5,
    ri: "1.370–1.470",
    sg: "1.98–2.25",
    crystal: "Amorphous (non-crystalline)",
    treatments: ["Sugar-acid treatment", "Smoke treatment", "Resin stabilization", "Doublet/triplet assembly"],
    origins: ["Australia (95% of world supply)", "Ethiopia", "Mexico", "Brazil", "USA"],
    description: "Hydrated silica with microscopic spheres that diffract light into spectral colors. Black opal from Lightning Ridge is the rarest and most valuable. Ethiopian opal is more porous.",
    priceRange: "$20–$1,000/ct (white); $500–$10,000+/ct (black opal)",
  },
  {
    name: "Amethyst",
    slug: "amethyst",
    category: "Semi-precious",
    color: "Purple (light lavender to deep violet)",
    mohs: 7,
    ri: "1.544–1.553",
    sg: "2.65",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat (to produce citrine or green)", "Irradiation"],
    origins: ["Brazil", "Zambia", "Uruguay", "Russia", "South Korea", "USA"],
    description: "Purple variety of quartz. Deep Siberian color with red flashes is most valued. Amethyst is abundant and affordable, but fine deep color is scarcer.",
    priceRange: "$5–$20/ct (light); $20–$50/ct (deep Siberian); $50+/ct (rare AAA)",
  },
  {
    name: "Citrine",
    slug: "citrine",
    category: "Semi-precious",
    color: "Yellow to orange-brown",
    mohs: 7,
    ri: "1.544–1.553",
    sg: "2.65",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat (most citrine is heat-treated amethyst)"],
    origins: ["Brazil", "Madagascar", "Russia", "France", "USA"],
    description: "Yellow-to-orange quartz. Most citrine on the market is heat-treated amethyst or smoky quartz. Natural citrine is pale yellow and rare. Deep orange 'Madeira' color is most prized.",
    priceRange: "$5–$15/ct; $15–$40/ct (Madeira deep orange)",
  },
  {
    name: "Garnet",
    slug: "garnet",
    category: "Semi-precious",
    color: "Red, green, orange, yellow, purple, black, color-change",
    mohs: 6.5,
    ri: "1.714–1.940 (varies by species)",
    sg: "3.45–4.20",
    crystal: "Cubic (isometric)",
    treatments: ["Heat", "Irradiation"],
    origins: ["India", "Sri Lanka", "Tanzania", "Kenya", "Mali", "USA (Arizona)", "Madagascar"],
    description: "A large family with many species: pyrope (red), almandine (purple-red), spessartite (orange), grossular (green tsavorite, green demantoid), andradite (green demantoid).",
    priceRange: "$10–$100/ct (common red); $1,000–$8,000/ct (tsavorite); $3,000–$15,000/ct (demantoid)",
  },
  {
    name: "Topaz",
    slug: "topaz",
    category: "Semi-precious",
    color: "Colorless, blue, yellow, orange, pink, red, green",
    mohs: 8,
    ri: "1.606–1.638",
    sg: "3.49–3.57",
    crystal: "Orthorhombic",
    treatments: ["Irradiation + heat (to produce blue)", "Heat", "Coating"],
    origins: ["Brazil", "Pakistan", "Russia", "Mexico", "USA", "Sri Lanka"],
    description: "Hard silicate mineral. Imperial topaz (golden to pink-orange) is the most valuable. Blue topaz is almost always irradiated. Mystic topaz is coated for iridescence.",
    priceRange: "$5–$20/ct (blue); $50–$200/ct (fine imperial); $200–$500+/ct (pink)",
  },
  {
    name: "Tourmaline",
    slug: "tourmaline",
    category: "Semi-precious",
    color: "All colors — pink, green, blue, watermelon, red, yellow, black, colorless",
    mohs: 7,
    ri: "1.614–1.666",
    sg: "3.02–3.26",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat", "Irradiation", "Coating", "Fracture filling"],
    origins: ["Brazil", "Afghanistan", "Pakistan", "Madagascar", "USA (California)", "Nigeria", "Mozambique"],
    description: "Extremely versatile gem with more color varieties than any other. Paraíba tourmaline (neon blue-green) from Brazil is among the most expensive colored gems. Watermelon is pink-green zoned.",
    priceRange: "$20–$150/ct (pink/green); $1,000–$10,000/ct (Paraíba); $10,000–$50,000+/ct (fine Paraíba)",
  },
  {
    name: "Peridot",
    slug: "peridot",
    category: "Semi-precious",
    color: "Olive green to yellowish-green",
    mohs: 6.5,
    ri: "1.650–1.690",
    sg: "3.28–3.48",
    crystal: "Orthorhombic",
    treatments: ["None (peridot is typically untreated)"],
    origins: ["Myanmar", "Pakistan", "China", "USA (Arizona)", "Egypt", "Vietnam"],
    description: "The gem variety of olivine. Formed deep in the Earth's mantle and brought up by volcanic activity. Ancient source was Topazios Island (Egypt). Bright lime-green is most valued.",
    priceRange: "$10–$50/ct (fine); $50–$150/ct (large deep green)",
  },
  {
    name: "Aquamarine",
    slug: "aquamarine",
    category: "Semi-precious",
    color: "Blue to greenish-blue",
    mohs: 7.5,
    ri: "1.564–1.596",
    sg: "2.68–2.74",
    crystal: "Hexagonal (trigonal)",
    treatments: ["Heat (to remove green tones, enhance blue)"],
    origins: ["Brazil", "Madagascar", "Pakistan", "Nigeria", "Mozambique", "Sri Lanka"],
    description: "Blue variety of beryl. Named after seawater (aqua marina). Fine deep blue is most valuable, though most stones are pale. Large clean crystals are relatively common.",
    priceRange: "$20–$100/ct (fine); $100–$500/ct (deep Santa Maria blue)",
  },
  {
    name: "Moonstone",
    slug: "moonstone",
    category: "Semi-precious",
    color: "Colorless, white, peach, gray, rainbow with adularescence",
    mohs: 6,
    ri: "1.518–1.526",
    sg: "2.55–2.63",
    crystal: "Monoclinic",
    treatments: ["Oil or resin filling (to enhance adularescence)"],
    origins: ["Sri Lanka", "India", "Madagascar", "Myanmar", "Tanzania"],
    description: "A feldspar with adularescence — a floating blue-white glow that moves across the surface. Sri Lankan blue sheen moonstone is most prized. Rainbow moonstone is actually labradorite.",
    priceRange: "$10–$50/ct (fine); $50–$200/ct (blue sheen, large)",
  },
  {
    name: "Lapis Lazuli",
    slug: "lapis-lazuli",
    category: "Organic/ornamental",
    color: "Deep blue with gold pyrite flecks",
    mohs: 5.5,
    ri: "1.500",
    sg: "2.40–2.80",
    crystal: "Aggregate (rock, not mineral)",
    treatments: ["Dye enhancement (lower grades)", "Wax impregnation"],
    origins: ["Afghanistan (primary source for 6000+ years)", "Chile", "Russia (Siberia)", "Pakistan"],
    description: "A metamorphic rock composed mainly of lazurite with calcite and pyrite. Deep royal blue with few calcite veins and fine gold pyrite specks is most valued.",
    priceRange: "$2–$20/ct (standard); $20–$50+/ct (top grade — deep blue, minimal calcite)",
  },
  {
    name: "Jade",
    slug: "jade",
    category: "Organic/ornamental",
    color: "Green, white, lavender, yellow, orange, red, black",
    mohs: "6.5–7 (jadeite), 6–6.5 (nephrite)",
    ri: "1.64–1.67 (jadeite), 1.60–1.63 (nephrite)",
    sg: "3.30–3.38 (jadeite), 2.90–3.03 (nephrite)",
    crystal: "Monoclinic (aggregate)",
    treatments: ["Bleaching", "Dyeing", "Acid treatment", "Polymer impregnation", "Waxing"],
    origins: ["Myanmar (jadeite)", "Guatemala (jadeite)", "China (nephrite)", "Russia (nephrite)", "Canada (nephrite)", "New Zealand (nephrite)"],
    description: "Two distinct minerals: jadeite and nephrite. Imperial jade — intense green, translucent jadeite — is the most valuable. Jade has deep cultural significance in China for over 5000 years.",
    priceRange: "$10–$100/ct (nephrite); $100–$5,000/ct (jadeite); $5,000–$50,000+/ct (Imperial green)",
  },
  {
    name: "Alexandrite",
    slug: "alexandrite",
    category: "Precious",
    color: "Green (daylight) to red/purple (incandescent light)",
    mohs: 8.5,
    ri: "1.741–1.760",
    sg: "3.70–3.78",
    crystal: "Orthorhombic",
    treatments: ["None (color-change is natural)"],
    origins: ["Russia (Ural Mountains — original source)", "Sri Lanka", "Brazil", "Tanzania", "India", "Madagascar"],
    description: "A rare color-change variety of chrysoberyl. Green in daylight, red in incandescent light. Russian alexandrite with strong color change is the most valuable. Fine stones are extremely rare.",
    priceRange: "$1,000–$10,000/ct (fine); $10,000–$50,000+/ct (Russian, strong color change)",
  },
  {
    name: "Turquoise",
    slug: "turquoise",
    category: "Organic/ornamental",
    color: "Sky blue to blue-green to green",
    mohs: 5,
    ri: "1.61–1.65",
    sg: "2.60–2.80",
    crystal: "Triclinic (cryptocrystalline)",
    treatments: ["Stabilization (resin)", "Dyeing", "Reconstitution", "Zachery treatment"],
    origins: ["USA (Arizona, Nevada, New Mexico)", "Iran", "China", "Egypt (Sinai)", "Tibet", "Mexico"],
    description: "A hydrated phosphate of copper and aluminum. The finest color is pure sky blue (Persian blue). Most turquoise is stabilized because it's naturally soft and porous.",
    priceRange: "$5–$30/ct (stabilized); $30–$100/ct (natural); $100–$500+/ct (natural high-grade Persian)",
  },
  {
    name: "Amber",
    slug: "amber",
    category: "Organic",
    color: "Yellow, orange, brown, red, green, blue, white",
    mohs: 2.5,
    ri: "1.539–1.545",
    sg: "1.05–1.10",
    crystal: "Amorphous (fossilized tree resin)",
    treatments: ["Heat (to clarify or produce sunspangles)", "Pressure (ambroid/pressed amber)", "Coating"],
    origins: ["Baltic region (Poland, Lithuania, Russia, 80% of world supply)", "Dominican Republic (blue amber)", "Myanmar", "Mexico", "Indonesia"],
    description: "Fossilized tree resin from ancient conifers, 40–90 million years old. Can contain insect or plant inclusions (inclusions add value). Baltic amber is the most common. Blue amber is rare.",
    priceRange: "$10–$100/ct (standard); $100–$500/ct (with insect inclusions); $500+/ct (rare blue amber)",
  },
  {
    name: "Spinel",
    slug: "spinel",
    category: "Semi-precious",
    color: "Red, blue, pink, purple, orange, black, color-change",
    mohs: 8,
    ri: "1.712–1.730",
    sg: "3.54–3.63",
    crystal: "Cubic (isometric)",
    treatments: ["None (spinel is typically untreated)"],
    origins: ["Myanmar", "Sri Lanka", "Tajikistan", "Tanzania", "Vietnam", "Afghanistan"],
    description: "A natural gem often confused with ruby and sapphire throughout history (the 'Black Prince's Ruby' is actually spinel). Red spinel is most valuable. Neon cobalt-blue spinel is highly sought.",
    priceRange: "$50–$500/ct (fine); $500–$3,000/ct (red/neon blue); $3,000–$10,000/ct (large fine red)",
  },
  {
    name: "Zircon",
    slug: "zircon",
    category: "Semi-precious",
    color: "Colorless, blue, red, orange, yellow, green, brown",
    mohs: 7.5,
    ri: "1.777–1.987",
    sg: "4.60–4.80",
    crystal: "Tetragonal",
    treatments: ["Heat (to produce blue, colorless, golden colors)"],
    origins: ["Cambodia", "Sri Lanka", "Myanmar", "Thailand", "Australia (Argyle)", "Tanzania"],
    description: "A natural gem with high dispersion (fire) and luster that rivals diamond. Heat-treated blue zircon is most popular. Not to be confused with cubic zirconia (CZ) — a synthetic material.",
    priceRange: "$20–$100/ct (blue); $100–$400/ct (fine red/orange); $400+/ct (rare green)",
  },
  {
    name: "Chrysoberyl",
    slug: "chrysoberyl",
    category: "Precious",
    color: "Yellow, green, brown, colorless",
    mohs: 8.5,
    ri: "1.741–1.760",
    sg: "3.70–3.78",
    crystal: "Orthorhombic",
    treatments: ["None (typically untreated)"],
    origins: ["Brazil", "Sri Lanka", "Madagascar", "Tanzania", "India", "China"],
    description: "A very hard durable gem. Ordinary chrysoberyl is yellow-green and affordable. The highly prized cat's-eye chrysoberyl (cymophane) displays sharp chatoyancy. Alexandrite is the color-change variety.",
    priceRange: "$20–$100/ct (yellow-green); $500–$5,000/ct (cat's-eye); $1,000–$10,000/ct (fine cat's-eye)",
  },
  {
    name: "Pearl",
    slug: "pearl",
    category: "Organic",
    color: "White, cream, pink, silver, gold, black, green, blue",
    mohs: 2.5,
    ri: "1.530–1.685",
    sg: "2.60–2.85",
    crystal: "Amorphous (biogenic calcium carbonate)",
    treatments: ["Bleaching", "Dyeing", "Irradiation", "Coating", "Fracture filling"],
    origins: ["Japan (Akoya cultured)", "French Polynesia (Tahitian cultured)", "Australia (South Sea)", "Philippines/Indonesia (South Sea)", "China (freshwater cultured)"],
    description: "Created by mollusks depositing nacre around an irritant. Natural pearls are extremely rare. Cultured pearls: Akoya (classic round white), Tahitian (dark exotic), South Sea (large golden/white), freshwater (varied shapes/colors).",
    priceRange: "$50–$500 (Akoya strand); $500–$5,000 (South Sea/Tahitian); $5,000–$50,000+ (natural pearl)",
  },
  {
    name: "Coral",
    slug: "coral",
    category: "Organic",
    color: "Red, pink, white, black, gold",
    mohs: 3,
    ri: "1.486–1.658",
    sg: "2.60–2.70",
    crystal: "Amorphous (biogenic calcium carbonate)",
    treatments: ["Bleaching", "Dyeing", "Impregnation"],
    origins: ["Mediterranean Sea (red coral)", "Japan/Taiwan (pink coral)", "Hawaii (black/gold coral)"],
    description: "The skeleton of marine coral polyps. Precious coral (Corallium rubrum) in deep red is most valued. Overharvesting has made quality coral increasingly rare and restricted.",
    priceRange: "$10–$100/ct (pink); $100–$500/ct (deep red); $500+/ct (fine oxblood red)",
  },
];

export const categories = [...new Set(gemstones.map((g) => g.category))];
